version: "3.9"

services:
  appointment-proxy:
    image: wernight/ngrok
    env_file:
      - .env
    environment:
      - NGROK_LOOK_DOMAIN=appointment-tg-bot
      - NGROK_PORT=80
      - NGROK_DEBUG=1


networks:
  default:
    name: appointment-network
    external: true
